### ISSUE TITLE
why only 3 contributors ?

### ISSUE THREAD

**Issue by Walidmash** [facg3/todo-list#14]
you guys are team of 4 members, why only 3 contributors in this repository? where is the forth member?
![screenshot from 2017-11-18 06-20-37](https://user-images.githubusercontent.com/20396442/32976849-da174bbc-cc28-11e7-93c6-bc452f0ba6ac.png)

**Comment by marwa7med** [comment]
she was sick :(

**Comment by Walidmash** [comment]
oh, sorry for her
