### ISSUE TITLE
cloneArrayOfObjects function returns a string!

### ISSUE THREAD

**Issue by Walidmash** [facg3/todo-list#22]
[cloneArrayOfObjects](https://github.com/facg3/todo-list/blob/fac587460e89f472782ee0e6edcce65c2bc65ddd/logic.js#L20) function should make a copy of the array not making a string copy of it, and you dont need to use map to make a clone, you should read more about cloning objects and arrays

**Comment by ZooeyMiller** [comment]
`cloneArrayOfObjects` was a pre-supplied function for this cohort, it returns a new array with all of the objects inside cloned. This team didn't write the function, and it does work as intended. 

[See this repl for clarity](https://repl.it/@zooeyxmiller/clone-array-of-objects-explanation)
