### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by ZooeyMiller** [facg3/todo-list#25]
You have 4 failing tests when I run `npm test`. 

The topic of the week is testing so it would be much better to get all of your tests working and reliable, before moving onto something like styling with css, which isn't quite as important this week. 

This is definitely a priority when you respond to issues in my opinion.

**Comment by MMortaga** [comment]
True. We'll get this fixed now.

**Comment by MMortaga** [comment]
@ZooeyMiller Please consider taking a look now and let us know if this is still an issue.

**Comment by ZooeyMiller** [comment]
:+1: LGTM.
