### ISSUE TITLE
all of your tests are described as 'tape is working'

### ISSUE THREAD

**Issue by ZooeyMiller** [facg3/todo-list#26]
The description of each test (the string which is the first argument to the `test` function) should describe what the test is doing. Currently all of the descriptions are the same.

**Comment by MMortaga** [comment]
Yeah, we should've altered the description to something more informative. Thanks for pointing this out Zooey.

**Comment by MMortaga** [comment]
Fixed now!

**Comment by ZooeyMiller** [comment]
Awesome! Looked at the code, looks good to me, just remember to `relate` the issue a piece of work is concerning in the commit and the PR.
